version: 0.2
        
phases:
  install:
    runtime-versions:
      java: 1.8
env:
  parameter-store:
    DOCKER_USERNAME: java/dockerhub/username
    DOCKER_PASSWORD: java/dockerhub/password

    # steps:
  build:
    commands:
      - mvn package
      - docker build -t cal .
      - docker tag cal anilkumare/cal
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push anilkumare/cal
  post_build:
    commands:
      - echo "pipeline created successfully"
