version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /Java/dockerhub_credentials/username
    DOCKER_PASSWORD: /Java/dockerhub_credentials/password
phases:
  install:
    runtime-versions:
      java: latest
      
  build:
    commands:
      - mvn package
      - docker build -t cal .
      - docker tag cal anilkumare/cal
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push anilkumare/cal
  post_build:
      commands:
        - echo "pipeline created successfully"
